server:
  port: 8080

  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:amething;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa

jwt:
  accessTokenExpireTime: PT1H
  refreshTokenExpireTime: P30D
  secretKey: asdjfioasejfoiasdjfoicjv
  type: Bearer
